filter:
    excluded_paths:
        - */tests/*
checks:
    python:
        code_rating: true
        duplication: true
tools:
    pylint:
        python_version: 2     # Possible values: 2, 3
        config_file: '.pylintrc'
    external_code_coverage: true
    sensiolabs_security_checker: true
