filter:
    excluded_paths:
        - tests/*
checks:
    python:
      code_rating: true
      duplicate_code: true

tools:
    pylint:
        python_version: 2     # Possible values: 2, 3
        config_file: '.pylintrc'
    external_code_coverage:
        timeout: 600    # Timeout in seconds.
    sensiolabs_security_checker: true
